import Head from 'next/head';
import { useState } from 'react';
import { Button, Divider, Input } from '@statisticsnorway/ssb-component-library';
import data from './nameSearchPop300';

export default function Home() {
  //Henter ut navnedata fra JSON
  const nameData = data.response.docs;
  //Resultat av søk
  const [result, setResult] = useState([]);

  //Funksjon for å søke etter navn
  function SearchName(param) {
    //Array som skal holde på navnefakta
    let text = [];
    //Avbryter om argumentet er en tom string
    if (param === "") { setResult(text); return; }
    //Splitter opp navn, setter hvert enkelt navn til å ha stor forbokstav og liten skrift ellers
    let names = param.split(' ');
    names = names.map(n => n = n.charAt(0).toUpperCase() + n.slice(1).toLowerCase());
    //Søker opp det fulle navnet hvis det er mer enn et navn for å legge til fakta om hvor mange som heter det. Et fullt navn er lagt til i JSON: Gro Hansen
    if (names.length > 1) {
      let fullNameRes = nameData.find(n => n.name === names.join(" ").toUpperCase());
      if (fullNameRes && fullNameRes.type === "full") text.push(`Det er ${fullNameRes.count > 3 ? fullNameRes.count : "0-3"} personer som har ${names.join(" ")} som fornavn og etternavn.`);
    }
    //Søker i database for hvert enkelt navn i søket
    names.forEach(name => {
      let searchRes = nameData.filter(n => n.name === name.toUpperCase());
      //Sjekker hva slags type navn det er og legger til fakta tilpasset dette
      searchRes.map(x => {
        if (x.type === "firstgiven") text.push(`Det er ${x.count > 3 ? x.count : "0-3"} personer som har ${name} som fornavn.`);
        if (x.type === "onlygiven") text.push(`Det er ${x.count > 3 ? x.count : "0-3"} personer som bare har ${name} som fornavn.`);
        if (x.type === "family") text.push(`Det er ${x.count > 3 ? x.count : "0-3"} personer som har ${name} som etternavn.`);
      })
    });
    //Hvis ikke det var noen fakta som ble lagt til, altså ingen treff på søk, vil bruker få beskjed om at 0-3 personer har det navnet
    if (text.length === 0) text.push(`Det er 0-3 personer som heter ${names.join(" ")}.`);
    //Setter result til array med fakta
    setResult(text);
  }

  return (
    <div>
      <Head>
        <title>Navnesøk</title>
        <meta name="description" lang='no' content="Generated by create next app" />
      </Head>

      <main>
        {/* Søkefelt, trigger SearchName-funksjonen på callback */}
        <Input searchField label={"Skriv navnet ditt her"} submitCallback={SearchName} />
        {/* Resultat fra søk, vises bare om result har noe data */}
        {result.length > 0 ?
          <span>
            <h2>Resultat</h2>
            <Divider light />
            {/* Legger inn en <p> for hver setning lagret i result */}
            {result.map(n => <p>{n}</p>)}
          </span> : null}
      </main>
    </div>
  )
}
